### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by juliusyang97** [Media-Smart/vedadet#18]
`python configs/trainval/tinaface/test_widerface.py configs/trainval/tinaface/tinaface.py data/tinaface_r50_fpn_widerface.pth`

`loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[                                                  ] 0/55, elapsed: 0s, ETA:Traceback (most recent call last):
  File "configs/trainval/tinaface/test_widerface.py", line 101, in <module>
    main()
  File "configs/trainval/tinaface/test_widerface.py", line 96, in main
    results = test(engine, data_loader, args.outdir)
  File "configs/trainval/tinaface/test_widerface.py", line 77, in test
    result = engine(data)[0]
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yjq/Research_traning/vedadet/vedacore/parallel/data_parallel.py", line 30, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yjq/Research_traning/vedadet/vedadet/engines/val_engine.py", line 15, in forward
    return self.forward_impl(**data)
  File "/home/yjq/Research_traning/vedadet/vedadet/engines/val_engine.py", line 18, in forward_impl
    dets = self.infer(img, img_metas)
  File "/home/yjq/Research_traning/vedadet/vedadet/engines/infer_engine.py", line 115, in infer
    return self._simple_infer(img[0], img_metas[0])
  File "/home/yjq/Research_traning/vedadet/vedadet/engines/infer_engine.py", line 57, in _simple_infer
    dets = self._get_raw_dets(img, img_metas)
  File "/home/yjq/Research_traning/vedadet/vedadet/engines/infer_engine.py", line 36, in _get_raw_dets
    feats = self.extract_feats(img)
  File "/home/yjq/Research_traning/vedadet/vedadet/engines/infer_engine.py", line 24, in extract_feats
    feats = self.model(img, train=False)
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yjq/Research_traning/vedadet/vedadet/models/detectors/single_stage_detector.py", line 48, in forward
    feats = self.forward_impl(x)
  File "/home/yjq/Research_traning/vedadet/vedadet/models/detectors/single_stage_detector.py", line 35, in forward_impl
    feats = self.backbone(x)
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yjq/Research_traning/vedadet/vedadet/models/backbones/resnet.py", line 624, in forward
    x = self.norm1(x)
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 245, in forward
    return F.group_norm(
  File "/home/yjq/miniconda3/envs/vedadet/lib/python3.8/site-packages/torch/nn/functional.py", line 2111, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps,
RuntimeError: CUDA error: no kernel image is available for execution on the device`

**Comment by hxcai** [comment]
@juliusyang97 It may be pytorch and cuda problem, see [this](https://github.com/pytorch/pytorch/issues/31285) for details.

**Comment by juliusyang97** [comment]
> @juliusyang97 It may be pytorch and cuda problem, see [this](https://github.com/pytorch/pytorch/issues/31285) for details.

thanks ,
