### ISSUE TITLE
ImportError: cannot import name 'deform_conv_ext'

### ISSUE THREAD

**Issue by jodie2235337** [Media-Smart/vedadet#32]
Reproduce TinaFace fellow https://github.com/Media-Smart/vedadet/tree/main/configs/trainval/tinaface/README.md
Evaluation(b): python configs/trainval/tinaface/test_widerface.py configs/trainval/tinaface/tinaface.py weight_path
Error message was as fellow. Anyone have the same problem ??? Thank you for answering~~~
Traceback (most recent call last):
  File "test_widerface.py", line 9, in <module>
    from vedadet.datasets import build_dataloader, build_dataset
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/__init__.py", line 1, in <module>
    from . import assembler, bridge, criteria, datasets, engines, misc, models, ops
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/assembler/__init__.py", line 1, in <module>
    from .trainval import trainval
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/assembler/trainval.py", line 6, in <module>
    from vedadet.datasets import build_dataloader, build_dataset
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/datasets/__init__.py", line 2, in <module>
    from .coco import CocoDataset
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/datasets/coco.py", line 14, in <module>
    from .custom import CustomDataset
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/datasets/custom.py", line 9, in <module>
    from .pipelines import Compose
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/datasets/pipelines/__init__.py", line 8, in <module>
    from .transforms import (Albu, Expand, MinIoURandomCrop, Normalize, Pad,
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/datasets/pipelines/transforms.py", line 9, in <module>
    from vedadet.misc.bbox import bbox_overlaps
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/misc/bbox/__init__.py", line 1, in <module>
    from .assigners import MaxIoUAssigner
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/misc/bbox/assigners/__init__.py", line 1, in <module>
    from .approx_max_iou_assigner import ApproxMaxIoUAssigner
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/misc/bbox/assigners/approx_max_iou_assigner.py", line 6, in <module>
    from ..iou_calculators import build_iou_calculator
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/misc/bbox/iou_calculators/__init__.py", line 2, in <module>
    from .iou2d_calculator import BboxOverlaps2D
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/misc/bbox/iou_calculators/iou2d_calculator.py", line 4, in <module>
    from ..bbox import bbox_overlaps
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/misc/bbox/bbox.py", line 6, in <module>
    from vedadet.ops import batched_nms
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/dfsdata2/jiangjl5_data/vedadet/vedadet/ops/dcn/deform_conv.py", line 11, in <module>
    from . import deform_conv_ext
ImportError: cannot import name 'deform_conv_ext'

**Comment by ZHUANGHP** [comment]
encounting the same error...

**Comment by jodie2235337** [comment]
@ZHUANGHP this bug may casued by low pytorch or cuda version. 
PyTorch 1.6.0 or higher
CUDA 10.2 or higher

Check issue #8 for solution
I'm working on it, and update later

**Comment by ZHUANGHP** [comment]
@jodie2235337 I have tried with a cuda version of 10.2 and PyTorch 1.7.1, same error.

**Comment by mileistone** [comment]
> @jodie2235337 I have tried with a cuda version of 10.2 and PyTorch 1.7.1, same error.

have you compiled it?

**Comment by ZHUANGHP** [comment]
> > @jodie2235337 I have tried with a cuda version of 10.2 and PyTorch 1.7.1, same error.
> 
> have you compiled it?

Compile cuda? Does PyTorch or cuda need compiling? Thought only C++ programs require this. I have tried several machines for different cuda version (cuda10.1, 10.2) and different PyTorch version (1.6, 1.7). Some error.

**Comment by jodie2235337** [comment]
@ZHUANGHP 
problem solving by:
cd vedadet
pip install -v -e .
reference: https://blog.csdn.net/qq_35975447/article/details/110430390 (Chinese version, hope you don't mind)

**Comment by chenzhengnan** [comment]
> @ZHUANGHP
> problem solving by:
> cd vedadet
> pip install -v -e .
> reference: https://blog.csdn.net/qq_35975447/article/details/110430390 (Chinese version, hope you don't mind)
答主你好，我执行了 pip install -v -e .之后，还是有同样的问题，请问是不是还有什么别的操作。

**Comment by ZHUANGHP** [comment]
> @ZHUANGHP
> problem solving by:
> cd vedadet
> pip install -v -e .
> reference: https://blog.csdn.net/qq_35975447/article/details/110430390 (Chinese version, hope you don't mind)

Thanks!

**Comment by cserezwan** [comment]
Hello, I followed this link: https://blog.csdn.net/qq_35975447/article/details/110430390
but still the same error. Any solution?
I'm using CUDA 10.1, do I need to try with 10.2?
