### ISSUE TITLE
building nms ops fails during installation

### ISSUE THREAD

**Issue by manisoftwartist** [Media-Smart/vedadet#53]
The command `pip install -v -e. --log piplog.txt`, the installation fails while trying to build the `nms` related parts. 

```
2021-05-31T08:51:28,118 Using pip 21.1.1 from /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip (python 3.8)
2021-05-31T08:51:28,124 Non-user install because site-packages writeable
2021-05-31T08:51:28,368 Created temporary directory: /tmp/pip-ephem-wheel-cache-f0e1dx_v
2021-05-31T08:51:28,368 Created temporary directory: /tmp/pip-req-tracker-h4kqazup
2021-05-31T08:51:28,369 Initialized build tracking at /tmp/pip-req-tracker-h4kqazup
2021-05-31T08:51:28,369 Created build tracker: /tmp/pip-req-tracker-h4kqazup
2021-05-31T08:51:28,369 Entered build tracker: /tmp/pip-req-tracker-h4kqazup
2021-05-31T08:51:28,369 Created temporary directory: /tmp/pip-install-u38ho2hv
2021-05-31T08:51:28,399 Obtaining file:///home_nfs/manuel/gal/vedadet
2021-05-31T08:51:28,400   Added file:///home_nfs/manuel/gal/vedadet to build tracker '/tmp/pip-req-tracker-h4kqazup'
2021-05-31T08:51:28,400     Running setup.py (path:/home_nfs/manuel/gal/vedadet/setup.py) egg_info for package from file:///home_nfs/manuel/gal/vedadet
2021-05-31T08:51:28,400     Created temporary directory: /tmp/pip-pip-egg-info-y9fhdtti
2021-05-31T08:51:28,400     Running command python setup.py egg_info
2021-05-31T08:51:30,710     running egg_info
2021-05-31T08:51:30,711     creating /tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info
2021-05-31T08:51:30,711     writing /tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/PKG-INFO
2021-05-31T08:51:30,712     writing dependency_links to /tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/dependency_links.txt
2021-05-31T08:51:30,712     writing requirements to /tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/requires.txt
2021-05-31T08:51:30,712     writing top-level names to /tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/top_level.txt
2021-05-31T08:51:30,712     writing manifest file '/tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/SOURCES.txt'
2021-05-31T08:51:30,871     reading manifest file '/tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/SOURCES.txt'
2021-05-31T08:51:30,874     writing manifest file '/tmp/pip-pip-egg-info-y9fhdtti/vedadet.egg-info/SOURCES.txt'
2021-05-31T08:51:31,088   Source in /home_nfs/manuel/gal/vedadet has version 0.1.0, which satisfies requirement vedadet==0.1.0 from file:///home_nfs/manuel/gal/vedadet
2021-05-31T08:51:31,088   Removed vedadet==0.1.0 from file:///home_nfs/manuel/gal/vedadet from build tracker '/tmp/pip-req-tracker-h4kqazup'
2021-05-31T08:51:31,131 Requirement already satisfied: addict in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (2.4.0)
2021-05-31T08:51:31,132 Requirement already satisfied: terminaltables in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (3.1.0)
2021-05-31T08:51:31,133 Requirement already satisfied: opencv-python in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (4.5.2.52)
2021-05-31T08:51:31,134 Requirement already satisfied: torchvision>=0.7.0 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (0.9.1)
2021-05-31T08:51:31,134 Requirement already satisfied: pyyaml in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (5.4.1)
2021-05-31T08:51:31,135 Requirement already satisfied: yapf in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (0.31.0)
2021-05-31T08:51:31,136 Requirement already satisfied: imagecorruptions in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (1.1.2)
2021-05-31T08:51:31,137 Requirement already satisfied: mmpycocotools in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from vedadet==0.1.0) (12.0.3)
2021-05-31T08:51:31,142 Requirement already satisfied: numpy in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (1.20.3)
2021-05-31T08:51:31,143 Requirement already satisfied: pillow>=4.1.1 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (8.2.0)
2021-05-31T08:51:31,144 Requirement already satisfied: torch==1.8.1 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (1.8.1)
2021-05-31T08:51:31,148 Requirement already satisfied: typing-extensions in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from torch==1.8.1->torchvision>=0.7.0->vedadet==0.1.0) (3.10.0.0)
2021-05-31T08:51:31,158 Requirement already satisfied: scipy>=1.2.1 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from imagecorruptions->vedadet==0.1.0) (1.6.3)
2021-05-31T08:51:31,160 Requirement already satisfied: scikit-image>=0.15 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from imagecorruptions->vedadet==0.1.0) (0.18.1)
2021-05-31T08:51:31,217 Requirement already satisfied: PyWavelets>=1.1.1 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (1.1.1)
2021-05-31T08:51:31,219 Requirement already satisfied: networkx>=2.0 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2.5.1)
2021-05-31T08:51:31,220 Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (3.4.2)
2021-05-31T08:51:31,221 Requirement already satisfied: imageio>=2.3.0 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2.9.0)
2021-05-31T08:51:31,222 Requirement already satisfied: tifffile>=2019.7.26 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2021.4.8)
2021-05-31T08:51:31,240 Requirement already satisfied: cycler>=0.10 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (0.10.0)
2021-05-31T08:51:31,241 Requirement already satisfied: kiwisolver>=1.0.1 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (1.3.1)
2021-05-31T08:51:31,242 Requirement already satisfied: pyparsing>=2.2.1 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2.4.7)
2021-05-31T08:51:31,243 Requirement already satisfied: python-dateutil>=2.7 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2.8.1)
2021-05-31T08:51:31,247 Requirement already satisfied: six in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from cycler>=0.10->matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (1.16.0)
2021-05-31T08:51:31,268 Requirement already satisfied: decorator<5,>=4.3 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from networkx>=2.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (4.4.2)
2021-05-31T08:51:31,298 Requirement already satisfied: cython>=0.27.3 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from mmpycocotools->vedadet==0.1.0) (0.29.23)
2021-05-31T08:51:31,299 Requirement already satisfied: setuptools>=18.0 in /home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages (from mmpycocotools->vedadet==0.1.0) (52.0.0.post20210125)
2021-05-31T08:51:31,342 Created temporary directory: /tmp/pip-unpack-rprzhfke
	2021-05-31T08:51:31,347 Installing collected packages: vedadet
2021-05-31T08:51:31,350   Running setup.py develop for vedadet
2021-05-31T08:51:31,350     Running command /home_nfs/manuel/miniconda/envs/vedadet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home_nfs/manuel/gal/vedadet/setup.py'"'"'; __file__='"'"'/home_nfs/manuel/gal/vedadet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
2021-05-31T08:51:33,533     running develop
2021-05-31T08:51:33,673     running egg_info
2021-05-31T08:51:33,674     writing vedadet.egg-info/PKG-INFO
2021-05-31T08:51:33,735     writing dependency_links to vedadet.egg-info/dependency_links.txt
2021-05-31T08:51:33,742     writing requirements to vedadet.egg-info/requires.txt
2021-05-31T08:51:33,746     writing top-level names to vedadet.egg-info/top_level.txt
2021-05-31T08:51:33,887     reading manifest file 'vedadet.egg-info/SOURCES.txt'
2021-05-31T08:51:33,894     writing manifest file 'vedadet.egg-info/SOURCES.txt'
2021-05-31T08:51:33,899     running build_ext
2021-05-31T08:51:33,919     building 'vedadet.ops.nms.nms_ext' extension
2021-05-31T08:51:34,049     Emitting ninja build file /home_nfs/manuel/gal/vedadet/build/temp.linux-x86_64-3.8/build.ninja...
2021-05-31T08:51:34,050     Compiling objects...
2021-05-31T08:51:34,050     Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
2021-05-31T08:51:34,311     [1/1] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /home_nfs/manuel/gal/vedadet/build/temp.linux-x86_64-3.8/vedadet/ops/nms/src/cuda/nms_kernel.o.d -DWITH_CUDA -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include/TH -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home_nfs/manuel/miniconda/envs/vedadet/include/python3.8 -c -c /home_nfs/manuel/gal/vedadet/vedadet/ops/nms/src/cuda/nms_kernel.cu -o /home_nfs/manuel/gal/vedadet/build/temp.linux-x86_64-3.8/vedadet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
2021-05-31T08:51:34,311     FAILED: /home_nfs/manuel/gal/vedadet/build/temp.linux-x86_64-3.8/vedadet/ops/nms/src/cuda/nms_kernel.o
2021-05-31T08:51:34,311     /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /home_nfs/manuel/gal/vedadet/build/temp.linux-x86_64-3.8/vedadet/ops/nms/src/cuda/nms_kernel.o.d -DWITH_CUDA -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include/TH -I/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home_nfs/manuel/miniconda/envs/vedadet/include/python3.8 -c -c /home_nfs/manuel/gal/vedadet/vedadet/ops/nms/src/cuda/nms_kernel.cu -o /home_nfs/manuel/gal/vedadet/build/temp.linux-x86_64-3.8/vedadet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
2021-05-31T08:51:34,312     nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
2021-05-31T08:51:34,312     ninja: build stopped: subcommand failed.
2021-05-31T08:51:34,339     Traceback (most recent call last):
2021-05-31T08:51:34,339       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
2021-05-31T08:51:34,340         subprocess.run(
2021-05-31T08:51:34,340       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/subprocess.py", line 512, in run
2021-05-31T08:51:34,340         raise CalledProcessError(retcode, process.args,
2021-05-31T08:51:34,341     subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

2021-05-31T08:51:34,341     The above exception was the direct cause of the following exception:

2021-05-31T08:51:34,342     Traceback (most recent call last):
2021-05-31T08:51:34,342       File "<string>", line 1, in <module>
2021-05-31T08:51:34,342       File "/home_nfs/manuel/gal/vedadet/setup.py", line 119, in <module>
2021-05-31T08:51:34,342         setup(
2021-05-31T08:51:34,343       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
2021-05-31T08:51:34,343         return distutils.core.setup(**attrs)
2021-05-31T08:51:34,343       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/core.py", line 148, in setup
2021-05-31T08:51:34,343         dist.run_commands()
2021-05-31T08:51:34,344       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/dist.py", line 966, in run_commands
2021-05-31T08:51:34,344         self.run_command(cmd)
2021-05-31T08:51:34,344       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/dist.py", line 985, in run_command
2021-05-31T08:51:34,344         cmd_obj.run()
2021-05-31T08:51:34,344       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
2021-05-31T08:51:34,345         self.install_for_development()
2021-05-31T08:51:34,345       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
2021-05-31T08:51:34,345         self.run_command('build_ext')
2021-05-31T08:51:34,345       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/cmd.py", line 313, in run_command
2021-05-31T08:51:34,346         self.distribution.run_command(command)
2021-05-31T08:51:34,346       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/dist.py", line 985, in run_command
2021-05-31T08:51:34,346         cmd_obj.run()
2021-05-31T08:51:34,346       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
2021-05-31T08:51:34,347         _build_ext.run(self)
2021-05-31T08:51:34,347       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
2021-05-31T08:51:34,347         _build_ext.build_ext.run(self)
2021-05-31T08:51:34,347       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/command/build_ext.py", line 340, in run
2021-05-31T08:51:34,347         self.build_extensions()
2021-05-31T08:51:34,347       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
2021-05-31T08:51:34,348         build_ext.build_extensions(self)
2021-05-31T08:51:34,348       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
2021-05-31T08:51:34,348         _build_ext.build_ext.build_extensions(self)
2021-05-31T08:51:34,348       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
2021-05-31T08:51:34,348         self._build_extensions_serial()
2021-05-31T08:51:34,348       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
2021-05-31T08:51:34,348         self.build_extension(ext)
2021-05-31T08:51:34,349       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
2021-05-31T08:51:34,349         _build_ext.build_extension(self, ext)
2021-05-31T08:51:34,349       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
2021-05-31T08:51:34,349         objects = self.compiler.compile(sources,
2021-05-31T08:51:34,349       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
2021-05-31T08:51:34,349         _write_ninja_file_and_compile_objects(
2021-05-31T08:51:34,349       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
2021-05-31T08:51:34,349         _run_ninja_build(
2021-05-31T08:51:34,350       File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
2021-05-31T08:51:34,350         raise RuntimeError(message) from e
2021-05-31T08:51:34,350     RuntimeError: Error compiling objects for extension
2021-05-31T08:51:34,545 ERROR: Command errored out with exit status 1: /home_nfs/manuel/miniconda/envs/vedadet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home_nfs/manuel/gal/vedadet/setup.py'"'"'; __file__='"'"'/home_nfs/manuel/gal/vedadet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
2021-05-31T08:51:34,546 Exception information:
2021-05-31T08:51:34,546 Traceback (most recent call last):
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
2021-05-31T08:51:34,546     status = self.run(options, args)
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
2021-05-31T08:51:34,546     return func(self, options, args)
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 393, in run
2021-05-31T08:51:34,546     installed = install_given_reqs(
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 77, in install_given_reqs
2021-05-31T08:51:34,546     requirement.install(
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 758, in install
2021-05-31T08:51:34,546     install_editable_legacy(
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/operations/install/editable_legacy.py", line 44, in install_editable
2021-05-31T08:51:34,546     call_subprocess(
2021-05-31T08:51:34,546   File "/home_nfs/manuel/miniconda/envs/vedadet/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
2021-05-31T08:51:34,546     raise InstallationSubprocessError(proc.returncode, command_desc)
2021-05-31T08:51:34,546 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home_nfs/manuel/miniconda/envs/vedadet/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home_nfs/manuel/gal/vedadet/setup.py'"'"'; __file__='"'"'/home_nfs/manuel/gal/vedadet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
2021-05-31T08:51:34,565 Removed build tracker: '/tmp/pip-req-tracker-h4kqazup'

How do I resolve this? Are there some known workarounds to this issue? My cmake version is `3.13.2`. I am installing on an ubuntu18.04 machine.
```

**Comment by manisoftwartist** [comment]
I found the issue myself. If the machine is not equipped with CUDA 10.2, this issue happens and the nms related cuda code does not compile and causes this issue.
