### ISSUE TITLE
Missing THC/THC.h

### ISSUE THREAD

**Issue by Sean-Powell** [Media-Smart/vedadet#87]
`(vedadet_3_7) sean-powell@sean-powell-laptop:~/vedadet$ pip install -v -e .
Using pip 21.2.2 from /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/pip (python 3.7)
Obtaining file:///home/sean-powell/vedadet
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info
    writing /tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/dependency_links.txt
    writing requirements to /tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-zdcltqsb/vedadet.egg-info/SOURCES.txt'
Requirement already satisfied: addict in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (2.4.0)
Requirement already satisfied: terminaltables in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (3.1.10)
Requirement already satisfied: opencv-python in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (4.5.5.64)
Requirement already satisfied: torchvision>=0.7.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (0.12.0)
Requirement already satisfied: pyyaml in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (6.0)
Requirement already satisfied: yapf in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (0.32.0)
Requirement already satisfied: imagecorruptions in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (1.1.2)
Requirement already satisfied: mmpycocotools in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from vedadet==0.1.0) (12.0.3)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (9.0.1)
Requirement already satisfied: torch==1.11.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (1.11.0)
Requirement already satisfied: typing-extensions in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (4.2.0)
Requirement already satisfied: requests in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (2.27.1)
Requirement already satisfied: numpy in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from torchvision>=0.7.0->vedadet==0.1.0) (1.19.5)
Requirement already satisfied: scipy>=1.2.1 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from imagecorruptions->vedadet==0.1.0) (1.7.3)
Requirement already satisfied: scikit-image>=0.15 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from imagecorruptions->vedadet==0.1.0) (0.19.2)
Requirement already satisfied: PyWavelets>=1.1.1 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (1.3.0)
Requirement already satisfied: packaging>=20.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (21.3)
Requirement already satisfied: networkx>=2.2 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2.2)
Requirement already satisfied: imageio>=2.4.1 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2.18.0)
Requirement already satisfied: tifffile>=2019.7.26 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (2021.11.2)
Requirement already satisfied: decorator>=4.3.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from networkx>=2.2->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (5.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from packaging>=20.0->scikit-image>=0.15->imagecorruptions->vedadet==0.1.0) (3.0.8)
Requirement already satisfied: cython>=0.27.3 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from mmpycocotools->vedadet==0.1.0) (0.29.28)
Requirement already satisfied: setuptools>=18.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from mmpycocotools->vedadet==0.1.0) (61.2.0)
Requirement already satisfied: matplotlib>=2.1.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from mmpycocotools->vedadet==0.1.0) (3.5.1)
Requirement already satisfied: cycler>=0.10 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from matplotlib>=2.1.0->mmpycocotools->vedadet==0.1.0) (0.11.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from matplotlib>=2.1.0->mmpycocotools->vedadet==0.1.0) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from matplotlib>=2.1.0->mmpycocotools->vedadet==0.1.0) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from matplotlib>=2.1.0->mmpycocotools->vedadet==0.1.0) (4.33.3)
Requirement already satisfied: six>=1.5 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->mmpycocotools->vedadet==0.1.0) (1.16.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from requests->torchvision>=0.7.0->vedadet==0.1.0) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from requests->torchvision>=0.7.0->vedadet==0.1.0) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from requests->torchvision>=0.7.0->vedadet==0.1.0) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages (from requests->torchvision>=0.7.0->vedadet==0.1.0) (2.0.12)
Installing collected packages: vedadet
  Running setup.py develop for vedadet
    Running command /home/sean-powell/anaconda3/envs/vedadet_3_7/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sean-powell/vedadet/setup.py'"'"'; __file__='"'"'/home/sean-powell/vedadet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing vedadet.egg-info/PKG-INFO
    writing dependency_links to vedadet.egg-info/dependency_links.txt
    writing requirements to vedadet.egg-info/requires.txt
    writing top-level names to vedadet.egg-info/top_level.txt
    reading manifest file 'vedadet.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'vedadet.egg-info/SOURCES.txt'
    running build_ext
    building 'vedadet.ops.nms.nms_ext' extension
    Emitting ninja build file /home/sean-powell/vedadet/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    [1/1] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include/TH -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/sean-powell/anaconda3/envs/vedadet_3_7/include/python3.7m -c -c /home/sean-powell/vedadet/vedadet/ops/nms/src/cuda/nms_kernel.cu -o /home/sean-powell/vedadet/build/temp.linux-x86_64-3.7/vedadet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
    FAILED: /home/sean-powell/vedadet/build/temp.linux-x86_64-3.7/vedadet/ops/nms/src/cuda/nms_kernel.o
    /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include/TH -I/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/sean-powell/anaconda3/envs/vedadet_3_7/include/python3.7m -c -c /home/sean-powell/vedadet/vedadet/ops/nms/src/cuda/nms_kernel.cu -o /home/sean-powell/vedadet/build/temp.linux-x86_64-3.7/vedadet/ops/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
    /home/sean-powell/vedadet/vedadet/ops/nms/src/cuda/nms_kernel.cu:6:21: fatal error: THC/THC.h: No such file or directory
    compilation terminated.
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
        env=env)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/subprocess.py", line 468, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sean-powell/vedadet/setup.py", line 170, in <module>
        zip_safe=False)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
        build_ext.build_extensions(self)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/sean-powell/anaconda3/envs/vedadet_3_7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
ERROR: Command errored out with exit status 1: /home/sean-powell/anaconda3/envs/vedadet_3_7/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/sean-powell/vedadet/setup.py'"'"'; __file__='"'"'/home/sean-powell/vedadet/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

I am getting the above output when running `pip install -v -e .`

This appears to be being caused by `/home/sean-powell/vedadet/vedadet/ops/nms/src/cuda/nms_kernel.cu:6:21: fatal error: THC/THC.h: No such file or directory`

is there a specific verion of pytorch i should be using? i tried 1.1.0 but pip install reupgraded to 1.11.0 the output of conda list is below for the enviroment

`# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   1.0.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
black                     22.3.0                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    5.0.0                    pypi_0    pypi
ca-certificates           2022.3.29            h06a4308_1  
cachetools                5.0.0                    pypi_0    pypi
certifi                   2021.10.8        py37h06a4308_2  
cffi                      1.15.0           py37h7f8727e_0  
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.28                  pypi_0    pypi
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fastjsonschema            2.15.3                   pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
flake8                    4.0.1                    pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
google-auth               2.6.6                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.44.0                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imagecorruptions          1.1.2                    pypi_0    pypi
imageio                   2.18.0                   pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
importlib-resources       5.7.1                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.13.0                   pypi_0    pypi
ipython                   7.33.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h7f8727e_0  
jsonschema                4.4.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.3.0                    pypi_0    pypi
jupyter-console           6.4.3                    pypi_0    pypi
jupyter-core              4.10.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
libedit                   3.1.20210910         h7f8727e_0  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
llvmlite                  0.31.0                   pypi_0    pypi
lyft-dataset-sdk          0.0.8                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
mmpycocotools             12.0.3                   pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
nbclient                  0.6.0                    pypi_0    pypi
nbconvert                 6.5.0                    pypi_0    pypi
nbformat                  5.3.0                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.5                    pypi_0    pypi
networkx                  2.2                      pypi_0    pypi
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
notebook                  6.4.11                   pypi_0    pypi
numba                     0.48.0                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
nuscenes-devkit           1.1.9                    pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
openssl                   1.0.2u               h7b6447c_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.1.5                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1            py37h22f2fdc_0  
pip                       21.2.2           py37h06a4308_0  
platformdirs              2.5.2                    pypi_0    pypi
plotly                    5.7.0                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
plyfile                   0.7.4                    pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.29                   pypi_0    pypi
protobuf                  3.20.1                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.4                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyparsing                 3.0.8                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pytest                    7.1.2                    pypi_0    pypi
python                    3.7.0                h6e4f718_3  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
qtconsole                 5.3.0                    pypi_0    pypi
qtpy                      2.0.1                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-image              0.19.2                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                61.2.0           py37h06a4308_0  
shapely                   1.8.1.post1              pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tenacity                  8.0.1                    pypi_0    pypi
tensorboard               2.9.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.13.3                   pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
torch                     1.11.0                   pypi_0    pypi
torchvision               0.12.0                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
trimesh                   2.35.39                  pypi_0    pypi
typed-ast                 1.5.3                    pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
urllib3                   1.26.9                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.6.0                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_2  
zstd                      1.4.9                haebb681_0  `

**Comment by venki-lfc** [comment]
Faced a similar problem on Colab. It's cuda version is 11.1.  I reinstalled the pytorch packages to support with this version and now everything works fine.
`!pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by Sean-Powell** [comment]
@venki-lfc  what version of python are you using? also i can't find those specific versions on pip or anaconda any advice on where to find them?

**Comment by venki-lfc** [comment]
> @venki-lfc what version of python are you using? also i can't find those specific versions on pip or anaconda any advice on where to find them?

I used the default python version from Colab. You can check it out by opening a notebook from Colab. I just reinstalled the torch versions as mentioned above.
